### ISSUE TITLE
Storing data in hdf5

### ISSUE THREAD

**Issue by kfriedl** [Photon-Data/photon_hdf5_reading_examples#4]
I have a few questions how to store my data in hdf5 format. At the moment, the output file consists of 4 columns: first simple iteration, second an indication which laser is "on" (1: green, -1: red), third and forth column are then the photon counts from the APDs. There's a simple example file attached. Through your very nice documentation of how to create a photon hdf5 file, I'm able to do that, but unfortunately I'm not sure how to use the parameters. How should I to convert my file to fit into the 'photon_data' dictionary in a photon-hdf5 file correctly? Also what is meant by ALEX_offset and what is the difference between ALEX_period and and ALEX_excitation_period exactly?
[ALEX_outputfile.txt](https://github.com/Photon-HDF5/photon_hdf5_reading_examples/files/951184/ALEX_outputfile.txt)

**Comment by tritemio** [comment]
@kfriedl , take a look at this notebook:

https://github.com/Photon-HDF5/phconvert/blob/master/notebooks/Writing%20Photon-HDF5%20files.ipynb

It creates a "dummy" smFRET Photon-HDF5 file from scratch and shows how to build the data dictionary that you need to pass to `save_photon_hdf5()`.

In your case, you can load the detector column in a numpy array and then replace -1 with 0 and convert to uint8 data type. For example if you load the detector column on `det` you can do:
```
det[det == -1] = 0
det = det.astype('unit8')
```
However, I now realize that you said **counts**! You cannot store counts (i.e. the binned number of photons) in Photon-HDF5. You need to acquire **timestamps**, that is a value for each detected photon, usually with a 10-100ns resolution. Using binned data, or counts, greatly limits the possibilities of the analysis.

In some cases, people do simple analysis by binning photons of freely-diffusing molecules with 1ms time bin. But I'm not aware of people **saving** binned data as part of the acquisition. This is because once data is binned, information is lost, and also because with 1ms time bin you are going to have bigger data files than when saving timestamps under normal single-molecule conditions.

But I don't know anything about you application, so maybe binning in your case make sense?

**Comment by tritemio** [comment]
BTW, regarding the difference between `alex_period` and `alex_excitation_period1`. The first is the ALEX alternation period in timestamps units (i.e. 4000, for a 50us ALEX period using 12.5ns timestamps).
The second contains the definition (start-stop values) of the Donor excitation period. `alex_excitation_period2 ` contains the definition of the Acceptor excitation period and so on.

Documentation:
http://photon-hdf5.readthedocs.io/en/0.4/phdata.html#measurement-specs

**Comment by kfriedl** [comment]
Hi Antonino,
Thank you very much for the explanation! I now switched to storing timestamps of photons instead of binning the photons. What's still intriguing me, is that photon-HDF5 ALEX file examples only contain a single column array as timestamp data. My application stores the information from each detector in a separate array (also to take account of rollovers). Is the trick simply fusing the arrays together and sort in time?

**Comment by tritemio** [comment]
@kfriedl , yes fusing and sorting will work. Typically the acquisition board will transfer data in the form of pairs (timestamp, detector) so it is pretty natural storing two arrays one for timestamps and one for detectors. Plus, when you do burst search you need both and if they were in separate arrays you would need to merge them. That's the reason Photon-HDF5 stores a single array of timestamps and an array of detetector number.

Merging is easy, just use `np.hstack` to concatenate both timestamps and detectors, then `np.argsort(kind='mergesort')` to get the sorted index. Then you can then use the sorted index to sort both timestamps and detectors.

**Comment by tritemio** [comment]
Example of merging timestamps and creating a detectors array ("mask") [here](https://github.com/tritemio/niconverter/blob/4870b2778055438b38e4786aa0928bef4e39c6f6/niconverter/niconverter.py#L456).

**Comment by kfriedl** [comment]
That works perfectly! Thanks a lot!

**Comment by tritemio** [comment]
You are welcome!
